# 1.write

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\shrut\Downloads\student_performance_ml.csv")

In [3]:
df.head()

,StudyHours,Attendance,PreviousScore,AssignmentsCompleted,SleepHours,FinalResult
0,2.0,65,45,3,5,0
1,3.0,70,50,4,6,0
2,4.0,75,55,5,6,0
3,5.0,80,60,6,7,1
4,6.0,85,65,7,7,1

In [4]:
df.tail()

,StudyHours,Attendance,PreviousScore,AssignmentsCompleted,SleepHours,FinalResult
25,5.2,81,61,6,7,1
26,6.2,87,66,7,7,1
27,7.2,91,72,8,8,1
28,8.2,96,78,9,8,1
29,1.8,63,44,2,5,0

In [6]:
df.shape

(30, 6)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudyHours            30 non-null     float64
 1   Attendance            30 non-null     int64
 2   PreviousScore         30 non-null     int64
 3   AssignmentsCompleted  30 non-null     int64
 4   SleepHours            30 non-null     int64
 5   FinalResult           30 non-null     int64
dtypes: float64(1), int64(5)
memory usage: 1.5 KB

In [9]:
df.columns

Index(['StudyHours', 'Attendance', 'PreviousScore', 'AssignmentsCompleted',
       'SleepHours', 'FinalResult'],
      dtype='object')